%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1024
image_height: 768
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 6.01724915e+02
   fy: 6.01596130e+02
   cx: 5.19341187e+02
   cy: 3.93778687e+02
